// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHr8JcQ_-EJHSjSt-dTUkK4xATGwG5vhA',
    appId: '1:101937395933:web:cc7525e0f44caa4b188334',
    messagingSenderId: '101937395933',
    projectId: 'footgal-aa376',
    authDomain: 'footgal-aa376.firebaseapp.com',
    storageBucket: 'footgal-aa376.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIbrAD6r2qb54EMW6kIjGh3dyZog49dq0',
    appId: '1:101937395933:android:a0f6dd8087266248188334',
    messagingSenderId: '101937395933',
    projectId: 'footgal-aa376',
    storageBucket: 'footgal-aa376.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv3AWl0PporTygLJyZWERlzjvh6wBkJXA',
    appId: '1:101937395933:ios:3b58a3dc15886566188334',
    messagingSenderId: '101937395933',
    projectId: 'footgal-aa376',
    storageBucket: 'footgal-aa376.appspot.com',
    iosClientId: '101937395933-pbu8qn36c75l5gctfb0h3gno5rclrfe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.footgal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv3AWl0PporTygLJyZWERlzjvh6wBkJXA',
    appId: '1:101937395933:ios:3b58a3dc15886566188334',
    messagingSenderId: '101937395933',
    projectId: 'footgal-aa376',
    storageBucket: 'footgal-aa376.appspot.com',
    iosClientId: '101937395933-pbu8qn36c75l5gctfb0h3gno5rclrfe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.footgal',
  );
}
